import { NextResponse } from "next/server"

const newArrivalsData = [
  {
    id: 1,
    title: "Elegant Floral Maxi Dress",
    image: "/images/dress1.webp",
    description:
      "Beautiful flowing maxi dress with delicate floral patterns. Perfect for summer occasions and evening events.",
    price: 89.99,
    originalPrice: 119.99,
    category: "Dresses",
    isNew: true,
    isBestseller: false,
    discount: 25,
    ratings: 4.8,
    reviewCount: 34,
    colors: ["Navy Blue", "Coral Pink", "Sage Green", "Cream White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["floral", "maxi", "elegant", "summer"],
    dateAdded: "2024-01-20",
  },
  {
    id: 2,
    title: "Chic Striped Knit Top",
    image: "/images/top1.png",
    description:
      "Comfortable and stylish striped knit top. Versatile piece that pairs well with jeans, skirts, or shorts.",
    price: 34.99,
    originalPrice: 44.99,
    category: "Tops",
    isNew: true,
    isBestseller: true,
    discount: 22,
    ratings: 4.6,
    reviewCount: 28,
    colors: ["Navy/White", "Black/White", "Red/White"],
    sizes: ["XS", "S", "M", "L"],
    tags: ["striped", "knit", "casual", "versatile"],
    dateAdded: "2024-01-18",
  },
  {
    id: 3,
    title: "Bohemian Off-Shoulder Blouse",
    image: "/images/top2.jpg",
    description: "Trendy off-shoulder blouse with bohemian flair. Features intricate embroidery and flowing sleeves.",
    price: 42.99,
    category: "Tops",
    isNew: true,
    isBestseller: false,
    ratings: 4.7,
    reviewCount: 19,
    colors: ["White", "Dusty Rose", "Sage Green"],
    sizes: ["S", "M", "L", "XL"],
    tags: ["bohemian", "off-shoulder", "embroidery", "trendy"],
    dateAdded: "2024-01-15",
  },
  {
    id: 4,
    title: "Classic A-Line Midi Dress",
    image: "/images/dress2.webp",
    description: "Timeless A-line midi dress in premium fabric. Perfect for office wear or casual outings.",
    price: 67.99,
    originalPrice: 89.99,
    category: "Dresses",
    isNew: true,
    isBestseller: true,
    discount: 24,
    ratings: 4.9,
    reviewCount: 42,
    colors: ["Black", "Navy", "Burgundy", "Forest Green"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    tags: ["classic", "a-line", "midi", "versatile"],
    dateAdded: "2024-01-12",
  },
  {
    id: 5,
    title: "Cropped Denim Jacket",
    image: "/images/top3.png",
    description: "Trendy cropped denim jacket with distressed details. Perfect layering piece for any season.",
    price: 56.99,
    category: "Tops",
    isNew: true,
    isBestseller: false,
    ratings: 4.4,
    reviewCount: 16,
    colors: ["Light Blue", "Dark Blue", "Black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["denim", "cropped", "jacket", "layering"],
    dateAdded: "2024-01-10",
  },
  {
    id: 6,
    title: "Romantic Lace Dress",
    image: "/images/dress6.png",
    description: "Delicate lace dress with romantic details. Ideal for special occasions and date nights.",
    price: 94.99,
    originalPrice: 129.99,
    category: "Dresses",
    isNew: true,
    isBestseller: true,
    discount: 27,
    ratings: 4.8,
    reviewCount: 31,
    colors: ["Blush Pink", "Ivory", "Dusty Blue"],
    sizes: ["XS", "S", "M", "L"],
    tags: ["lace", "romantic", "special occasion", "elegant"],
    dateAdded: "2024-01-08",
  },
  {
    id: 7,
    title: "Casual Cotton Tee",
    image: "/images/tops.jpg",
    description: "Soft cotton t-shirt with modern fit. Essential basic for everyday comfort and style.",
    price: 24.99,
    category: "Tops",
    isNew: true,
    isBestseller: false,
    ratings: 4.3,
    reviewCount: 22,
    colors: ["White", "Black", "Gray", "Pink", "Blue"],
    sizes: ["XS", "S", "M", "L", "XL"],
    tags: ["cotton", "basic", "casual", "comfortable"],
    dateAdded: "2024-01-05",
  },
  {
    id: 8,
    title: "Vintage Floral Sundress",
    image: "/images/Botom.webp",
    description: "Charming vintage-inspired sundress with beautiful floral print. Perfect for weekend adventures.",
    price: 52.99,
    originalPrice: 69.99,
    category: "Dresses",
    isNew: true,
    isBestseller: false,
    discount: 24,
    ratings: 4.5,
    reviewCount: 18,
    colors: ["Yellow Floral", "Blue Floral", "Pink Floral"],
    sizes: ["S", "M", "L", "XL"],
    tags: ["vintage", "floral", "sundress", "weekend"],
    dateAdded: "2024-01-03",
  },
]

export async function GET() {
  try {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 100))

    return NextResponse.json(newArrivalsData, {
      headers: {
        "Content-Type": "application/json",
        "Cache-Control": "no-store, max-age=0",
      },
    })
  } catch (error) {
    console.error("Error in new-arrivals API:", error)
    return NextResponse.json({ error: "Failed to fetch new arrivals" }, { status: 500 })
  }
}
