import { NextResponse } from "next/server"

const dresses = [
  {
    id: 1,
    title: "Floral Summer Dress",
    image: "/images/dress1.webp",
    description:
      "This beautiful floral summer dress is perfect for sunny days. Made with lightweight fabric and vibrant colors that will make you stand out.",
    price: "$49.99",
    priceValue: 49.99,
    originalPrice: "$69.99",
    ratings: ["⭐⭐⭐⭐⭐", "⭐⭐⭐⭐", "⭐⭐⭐⭐"],
    reviews: [
      "Absolutely love this dress! So comfortable and stylish. Perfect for summer outings. - Sama",
      "The colors are even prettier in person. Great quality fabric and excellent fit. - Haneen",
      "Perfect fit and true to size. Received many compliments wearing this. - Roaa",
    ],
    averageRating: 4.3,
    reviewCount: 28,
    category: "summer",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Floral Pink", "Floral Blue", "Floral Yellow"],
    isNew: false,
    isBestseller: true,
    isOnSale: true,
    fabric: "100% Cotton with floral print",
    care: ["Machine wash cold", "Hang dry", "Iron on low heat", "Do not bleach"],
  },
  {
    id: 2,
    title: "Elegant Evening Gown",
    image: "/images/dress2.webp",
    description:
      "Make a statement at your next special event with this elegant evening gown. Features sophisticated design and premium materials.",
    price: "$99.99",
    priceValue: 99.99,
    originalPrice: "$129.99",
    ratings: ["⭐⭐⭐⭐⭐", "⭐⭐⭐⭐", "⭐⭐⭐"],
    reviews: [
      "Received so many compliments wearing this gown. Absolutely stunning and well-made. - Hasaan",
      "The fit is perfect, and the fabric is high quality. Worth every penny. - Zuhour",
      "Great value for such a beautiful gown. Perfect for formal events. - Afnan",
    ],
    averageRating: 4.7,
    reviewCount: 15,
    category: "evening",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Emerald Green", "Navy Blue", "Burgundy"],
    isNew: true,
    isBestseller: false,
    isOnSale: true,
    fabric: "Polyester blend with satin finish",
    care: ["Dry clean only", "Store hanging", "Steam to remove wrinkles"],
  },
  {
    id: 3,
    title: "Casual Denim Dress",
    image: "/images/dress6.png",
    description:
      "Stay stylish and comfortable in this casual denim dress. Perfect for everyday wear with a modern twist on classic denim.",
    price: "$39.99",
    priceValue: 39.99,
    ratings: ["⭐⭐⭐⭐", "⭐⭐⭐", "⭐⭐"],
    reviews: [
      "Great casual dress for weekends. Love the fit and the quality of denim. - Fatima",
      "Good quality denim and true to size. Very comfortable for daily wear. - Lama",
      "Comfortable and versatile. Would recommend for casual occasions. - Sarah",
    ],
    averageRating: 3.7,
    reviewCount: 22,
    category: "casual",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Light Denim", "Dark Denim", "Black Denim"],
    isNew: false,
    isBestseller: false,
    isOnSale: false,
    fabric: "98% Cotton, 2% Elastane denim",
    care: ["Machine wash cold", "Tumble dry low", "Iron medium heat", "Wash inside out"],
  },
  {
    id: 4,
    title: "Bohemian Maxi Dress",
    image: "/images/dress.jpg",
    description:
      "Embrace your free spirit with this flowing bohemian maxi dress. Features vibrant patterns and comfortable loose fit.",
    price: "$59.99",
    priceValue: 59.99,
    originalPrice: "$79.99",
    ratings: ["⭐⭐⭐⭐⭐", "⭐⭐⭐⭐⭐", "⭐⭐⭐⭐"],
    reviews: [
      "Love the bohemian style and the flowing fabric. Perfect for festivals. - Maya",
      "Beautiful patterns and very comfortable. Great for vacation wear. - Nour",
      "Excellent quality and unique design. Highly recommend! - Layla",
    ],
    averageRating: 4.6,
    reviewCount: 19,
    category: "casual",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Yellow Print", "Orange Print", "Burgundy Print"],
    isNew: true,
    isBestseller: true,
    isOnSale: true,
    fabric: "Rayon blend with bohemian print",
    care: ["Hand wash cold", "Hang dry", "Iron on low", "Do not wring"],
  },
  {
    id: 5,
    title: "Classic Black Dress",
    image: "/images/dress2.webp",
    description:
      "Every wardrobe needs a classic black dress. This versatile piece can be dressed up or down for any occasion.",
    price: "$69.99",
    priceValue: 69.99,
    ratings: ["⭐⭐⭐⭐⭐", "⭐⭐⭐⭐", "⭐⭐⭐⭐⭐"],
    reviews: [
      "Perfect little black dress. Fits like a glove and very flattering. - Rania",
      "Great quality and timeless design. A wardrobe essential. - Dina",
      "Love how versatile this dress is. Can wear it anywhere. - Hala",
    ],
    averageRating: 4.8,
    reviewCount: 35,
    category: "formal",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Charcoal"],
    isNew: false,
    isBestseller: true,
    isOnSale: false,
    fabric: "Polyester blend with stretch",
    care: ["Machine wash cold", "Hang dry", "Iron medium heat", "Professional clean for best results"],
  },
  {
    id: 6,
    title: "Winter Wool Dress",
    image: "/images/dress1.webp",
    description:
      "Stay warm and stylish with this cozy wool dress. Perfect for colder months with elegant design and comfortable fit.",
    price: "$89.99",
    priceValue: 89.99,
    originalPrice: "$119.99",
    ratings: ["⭐⭐⭐⭐", "⭐⭐⭐⭐", "⭐⭐⭐"],
    reviews: [
      "Very warm and comfortable. Perfect for winter weather. - Amira",
      "Beautiful design and excellent quality wool. - Yasmin",
      "Great fit and keeps me warm all day. - Salma",
    ],
    averageRating: 4.2,
    reviewCount: 12,
    category: "winter",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Navy", "Camel", "Black"],
    isNew: true,
    isBestseller: false,
    isOnSale: true,
    fabric: "70% Wool, 30% Polyester blend",
    care: ["Dry clean only", "Store flat", "Use wool-safe detergent if hand washing"],
  },
]

export async function GET() {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500))

  return NextResponse.json(dresses, {
    headers: {
      "Content-Type": "application/json",
    },
  })
}
